Core_Proje/Core_Proje/Controllers/FeatureController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Proje.Controllers
{
    [Authorize(Roles = "Admin")]
    public class FeatureController : Controller
    {
        FeatureManager featureManager = new FeatureManager(new EfFeatureDal());

        [HttpGet]
        public IActionResult Index()
        {
            var values = featureManager.TGetByID(1);
            return View(values);
        }

        [HttpPost]
        public IActionResult Index(Feature feature)
        {

            FeatureValidator validations = new FeatureValidator();
            ValidationResult result = validations.Validate(feature);
            if (result.IsValid)
            {
                featureManager.TUpdate(feature);
                return RedirectToAction("Index","Default");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }
    }
}

Core_Proje/Core_Proje/Views/Feature/Index.cshtml
@model EntityLayer.Concrete.Feature

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("Index", "Feature", FormMethod.Post))
{
<form class="form-group" method="post">

    @Html.HiddenFor(x => x.FeatureID)
    <br />
    @Html.Label("Post Başlığı")
    @Html.TextBoxFor(x => x.Header, new { @class = "form-control", style = "color:yellow" })
    @Html.ValidationMessageFor(x => x.Header, "", new { @class = "text-danger" })

    @Html.Label("Adı")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control", style = "color:yellow" })
    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })

    @Html.Label("Ünvan")
    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", style = "color:yellow" })
    @Html.ValidationMessageFor(x => x.Title, "", new { @class = "text-danger" })
    <br />

    <button class="btn btn-outline-success">Güncelle</button>
</form>
}