Core_Proje/Core_Proje/Controllers/TestimonialController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core_Proje.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TestimonialController : Controller
    {
        TestimonialManager testimonialManager = new TestimonialManager(new EfTestimonialDal());
        public IActionResult Index()
        {
            var values = testimonialManager.TGetList();
            return View(values);
        }

        public IActionResult DeleteTestimonial(int id)
        {
            var values = testimonialManager.TGetByID(id);
            testimonialManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditTestimonial(int id)
        {
            var values = testimonialManager.TGetByID(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult EditTestimonial(Testimonial testimonial)
        {
            testimonialManager.TUpdate(testimonial);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddTestimonial()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddTestimonial(Testimonial testimonial)
        {
            testimonialManager.TAdd(testimonial);
            return RedirectToAction("Index");
        }
    }
}

Core_Proje/Core_Proje/Views/Testimonial/AddTestimonial.cshtml
@model EntityLayer.Concrete.Testimonial
@{
    ViewData["Title"] = "AddTestimonial";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<h3 class="mb-3">Yeni Referans Ekleme</h3>
@using (Html.BeginForm("AddTestimonial", "Testimonial", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description">Referans Ekleme Paneli</p>
                <form class="forms-sample">
                    <div class="form-group">
                        <label>Ad Soyad</label>
                        @Html.TextBoxFor(x => x.ClientName, new { @class = "form-control", style = "color:white" })
                    </div>
                    <div class="form-group">
                        <label>Unvan</label>
                        @Html.TextBoxFor(x => x.ClientBranch, new { @class = "form-control", style = "color:white" })
                    </div>
                    <div class="form-group">
                        <label>Şirket</label>
                        @Html.TextBoxFor(x => x.Company, new { @class = "form-control", style = "color:white" })
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        @Html.TextAreaFor(x => x.Comment, 5, 3, new { @class = "form-control", style = "color:white" })
                    </div>
                    <div class="form-group">
                        <label>Görsel URL</label>
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control", style = "color:white" })
                    </div>
                    <button type="submit" class="btn btn-outline-success mr-2">Kaydet</button>
                    <button type="button" class="btn btn-outline-danger" onclick="goBack()">İptal</button>
                    @*<button class="btn btn-outline-danger">İptal</button>*@
                </form>
            </div>

        </div>
    </div>
}

<script>
    function goBack() {
        window.history.back();
    }
</script>

Core_Proje/Core_Proje/Views/Testimonial/EditTestimonial.cshtml
@model EntityLayer.Concrete.Testimonial

@{
    ViewData["Title"] = "EditTestimonial";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<h3 class="mb-3">Referans Detayları</h3>
@using (Html.BeginForm("EditTestimonial", "Testimonial", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <p class="card-description">Referans Düzenleme Paneli</p>
                <form class="forms-sample">
                    <div class="form-group">
                        @Html.HiddenFor(x => x.TestimonialID)
                    </div>
                    <div class="form-group">
                        <label>Ad Soyad</label>
                        @Html.TextBoxFor(x => x.ClientName, new { @class = "form-control", style = "color:yellow" })
                    </div>
                    <div class="form-group">
                        <label>Unvan</label>
                        @Html.TextBoxFor(x => x.ClientBranch, new { @class = "form-control", style = "color:yellow" })
                    </div>
                    <div class="form-group">
                        <label>Şirket</label>
                        @Html.TextBoxFor(x => x.Company, new { @class = "form-control", style = "color:yellow" })
                    </div>
                    <div class="form-group">
                        <label>Açıklama</label>
                        @Html.TextAreaFor(x => x.Comment, 5, 3, new { @class = "form-control", style = "color:yellow" })
                    </div>
                    <div class="form-group">
                        <label>Görsel URL</label>
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control", style = "color:yellow" })
                    </div>
                    <button type="submit" class="btn btn-outline-success mr-2">Güncelle</button>
                    <button type="button" class="btn btn-outline-danger" onclick="goBack()">İptal</button>
                    @*<button class="btn btn-outline-danger">İptal</button>*@
                </form>
            </div>

        </div>
    </div>
}

<script>
    function goBack() {
        window.history.back();
    }
</script>

Core_Proje/Core_Proje/Views/Testimonial/Index.cshtml
@using EntityLayer.Concrete
@model List<Testimonial>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Referans Listesi</h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Görsel </th>
                                <th> Ad Soyad </th>
                                <th> Unvan </th>
                                <th> Şirket </th>
                                <th> Sil </th>
                                <th> Güncelle </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="@item.ImageUrl" alt="image" />
                                    </td>
                                    <td> @item.ClientName </td>
                                    <td> @item.ClientBranch </td>
                                    <td> @item.Company </td>
                                    <td style="text-align:center"><a class="btn btn-outline-danger" href="/Testimonial/DeleteTestimonial/@item.TestimonialID" onclick="return confirm('Silme İşlemini Onaylayın!');">Sil</a></td>
                                    <td style="text-align:center"><a href="/Testimonial/EditTestimonial/@item.TestimonialID" class="btn btn-outline-success">Güncelle</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    <a href="/Testimonial/AddTestimonial" class="btn btn-outline-warning">Yeni Referans Ekle</a>
                </div>
            </div>
        </div>
    </div>
</div>